apiVersion: v1    #8
kind: ConfigMap
metadata:
  name: {{ .Values.configFlask }} #flask-config
  namespace: default
  labels:
    app: {{ .Values.appFlask }} #flask
data:
  POSTGRES_DB: test
  POSTGRES_USER: postgres
  HOST: postgres