apiVersion: apps/v1     #5
kind: Deployment
metadata:
  name: {{ .Values.appPostgres }} #postgres
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appPostgres }} #postgres
  template:
    metadata:
      labels:
        app: {{ .Values.appPostgres }} #postgres
    spec:
      containers:
        - name: {{ .Values.appPostgres }} #postgres
          image: {{ .Values.postgresImage}}
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: {{ .Values.postgresPort }} #5432
          envFrom:
            - configMapRef:
                name: {{ .Values.configPostgres }} #postgres-config
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretPostgres }} #postgres-secret
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: {{ .Values.pvcPostgres }} #postgres-pv-claim
      volumes:
        - name: {{ .Values.pvcPostgres }} #postgres-pv-claim
          persistentVolumeClaim:
            claimName: {{ .Values.pvcPostgres }} 
